import { StyleSheet } from 'react-native';

export const lightColors = {
  background: '#f7f3ea',
  surface: '#fffaf1',
  surfaceStrong: '#ffffff',
  text: '#1f2526',
  muted: '#667074',
  line: '#d7d0c3',
  accent: '#006d77',
  accentStrong: '#00545c',
  accentSoft: '#d9f0ef',
  danger: '#a23b2a',
  warm: '#b66a1f',
  green: '#2c7a4b',
};

export const darkColors = {
  background: '#151918',
  surface: '#202624',
  surfaceStrong: '#2a312f',
  text: '#f2f5f3',
  muted: '#aab5b1',
  line: '#414b47',
  accent: '#5bbbc3',
  accentStrong: '#9ddde2',
  accentSoft: '#17383b',
  danger: '#df7b6d',
  warm: '#efb35c',
  green: '#7bd79d',
};

export type AppColors = typeof lightColors;

export function createStyles(colors: AppColors) {
  return StyleSheet.create({
    safeArea: { backgroundColor: colors.background, flex: 1 },
    container: { gap: 16, padding: 16, paddingBottom: 32 },
    header: {
      borderBottomColor: colors.line,
      borderBottomWidth: 1,
      gap: 10,
      paddingBottom: 16,
    },
    headerTopRow: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      gap: 12,
    },
    headerStatusRow: { alignItems: 'flex-end' },
    titleBlock: { flex: 1, gap: 4 },
    titleRow: { alignItems: 'center', flexDirection: 'row', gap: 10 },
    titleIcon: { borderRadius: 6, height: 32, width: 32 },
    eyebrow: { color: colors.accent, flexShrink: 1, fontSize: 12, fontWeight: '700' },
    title: { color: colors.text, flexShrink: 1, fontSize: 16, fontWeight: '700', lineHeight: 22 },
    menuButton: {
      alignItems: 'center',
      backgroundColor: colors.surfaceStrong,
      borderColor: colors.line,
      borderRadius: 8,
      borderWidth: 1,
      flexShrink: 0,
      height: 40,
      justifyContent: 'center',
      width: 44,
    },
    menuButtonText: { color: colors.text, fontSize: 22, fontWeight: '700', lineHeight: 24 },
    drawerBackdrop: {
      backgroundColor: '#00000070',
      flex: 1,
      flexDirection: 'row',
    },
    drawerPanel: {
      backgroundColor: colors.surfaceStrong,
      borderRightColor: colors.line,
      borderRightWidth: 1,
      elevation: 8,
      shadowColor: '#000000',
      shadowOffset: { height: 0, width: 4 },
      shadowOpacity: 0.22,
      shadowRadius: 12,
    },
    drawerDismissArea: { flex: 1 },
    drawerHeader: {
      alignItems: 'center',
      borderBottomColor: colors.line,
      borderBottomWidth: 1,
      backgroundColor: colors.surface,
      flexDirection: 'row',
      gap: 12,
      minHeight: 76,
      paddingHorizontal: 16,
      paddingVertical: 16,
    },
    drawerHeaderText: { flex: 1, gap: 2 },
    drawerHeaderTitle: { color: colors.text, fontSize: 18, fontWeight: '900' },
    drawerHeaderSubtitle: { color: colors.muted, fontSize: 12, fontWeight: '700', lineHeight: 16 },
    drawerItem: {
      alignItems: 'center',
      borderBottomColor: colors.line,
      borderBottomWidth: 1,
      flexDirection: 'row',
      gap: 12,
      minHeight: 56,
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    activeDrawerItem: { backgroundColor: colors.accentSoft },
    drawerActiveIndicator: {
      alignSelf: 'stretch',
      backgroundColor: colors.accent,
      borderRadius: 999,
      width: 4,
    },
    inactiveDrawerActiveIndicator: { backgroundColor: 'transparent' },
    drawerItemFallbackIcon: {
      color: colors.warm,
      fontSize: 18,
      fontWeight: '900',
      lineHeight: 22,
      textAlign: 'center',
      width: 22,
    },
    drawerItemText: { color: colors.text, flex: 1, fontSize: 16, fontWeight: '800' },
    activeDrawerItemText: { color: colors.accentStrong },
    connectionState: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.line,
      borderRadius: 999,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 8,
      minHeight: 36,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    connectedState: { backgroundColor: '#edf8f1', borderColor: '#8ab99b' },
    stateDot: { backgroundColor: colors.danger, borderRadius: 999, height: 11, width: 11 },
    connectedStateDot: { backgroundColor: colors.green },
    connectionStateText: { color: colors.muted, fontWeight: '700' },
    connectedStateText: { color: colors.green },
    screenHeading: { color: colors.text, fontSize: 24, fontWeight: '900', lineHeight: 30 },
    toolbar: { gap: 10 },
    toolbarActionRow: { flexDirection: 'row', gap: 10 },
    toolbarActionCell: { flex: 1 },
    button: {
      alignItems: 'center',
      backgroundColor: colors.surfaceStrong,
      borderColor: colors.line,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 8,
      justifyContent: 'center',
      minHeight: 48,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    primaryButton: { backgroundColor: colors.accent, borderColor: colors.accent },
    dangerButton: { backgroundColor: colors.danger, borderColor: colors.danger },
    selectedButton: { backgroundColor: colors.accentSoft, borderColor: colors.accent },
    disabledButton: { opacity: 0.46 },
    pressedButton: { opacity: 0.74 },
    transparentCameraButton: { backgroundColor: 'transparent', borderColor: '#ffffff75' },
    buttonText: { color: colors.text, fontSize: 16, fontWeight: '700', textAlign: 'center' },
    primaryButtonText: { color: '#ffffff' },
    dangerButtonText: { color: '#ffffff' },
    transparentCameraButtonText: {
      color: '#ffffff',
      textShadowColor: '#000000',
      textShadowOffset: { height: 1, width: 0 },
      textShadowRadius: 4,
    },
    buttonIcon: { color: colors.warm, fontSize: 22, fontWeight: '800' },
    transparentCameraButtonIcon: {
      color: '#ffffff',
      textShadowColor: '#000000',
      textShadowOffset: { height: 1, width: 0 },
      textShadowRadius: 4,
    },
    toggleControl: {
      alignItems: 'center',
      backgroundColor: colors.surfaceStrong,
      borderColor: colors.line,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      minHeight: 48,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    toggleText: { color: colors.text, fontSize: 16, fontWeight: '700' },
    devicePanel: { backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 8, borderWidth: 1, gap: 10, padding: 12 },
    sectionTitle: { color: colors.text, fontSize: 18, fontWeight: '800' },
    mutedText: { color: colors.muted, fontSize: 14 },
    deviceButton: { backgroundColor: colors.surfaceStrong, borderColor: colors.line, borderRadius: 8, borderWidth: 1, padding: 12 },
    deviceButtonText: { color: colors.text, fontWeight: '700' },
    connectedDeviceText: { color: colors.green, fontWeight: '700' },
    modalBackdrop: {
      alignItems: 'center',
      backgroundColor: '#00000080',
      flex: 1,
      justifyContent: 'center',
      padding: 18,
    },
    modalPanel: {
      backgroundColor: colors.surfaceStrong,
      borderColor: colors.line,
      borderRadius: 8,
      borderWidth: 1,
      gap: 14,
      maxWidth: 420,
      padding: 16,
      width: '100%',
    },
    modalTitle: { color: colors.text, fontSize: 18, fontWeight: '800' },
    modalText: { color: colors.muted, fontSize: 16, lineHeight: 22 },
    modeTabs: { borderBottomColor: colors.line, borderBottomWidth: 1, flexDirection: 'row', gap: 6, paddingBottom: 12 },
    modeTab: {
      alignItems: 'center',
      backgroundColor: colors.surfaceStrong,
      borderColor: colors.line,
      borderRadius: 8,
      borderWidth: 1,
      flex: 1,
      justifyContent: 'center',
      minHeight: 44,
      paddingHorizontal: 8,
    },
    activeModeTab: { backgroundColor: colors.accentSoft, borderColor: colors.accent },
    modeTabText: { color: colors.text, fontSize: 14, fontWeight: '700', textAlign: 'center' },
    activeModeTabText: { color: colors.accentStrong },
    panel: { gap: 12 },
    transparentCameraPanel: { backgroundColor: 'transparent' },
    cardPanelLandscape: { alignItems: 'flex-start', alignSelf: 'stretch', flexDirection: 'row' },
    compassGrid: { aspectRatio: 1, alignSelf: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 8, maxWidth: 460 },
    compassCell: { width: '31.8%' },
    compassCenter: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.line,
      borderRadius: 8,
      borderWidth: 1,
      justifyContent: 'center',
      minHeight: 72,
      width: '31.8%',
    },
    compassCenterText: { color: colors.muted, fontSize: 24, fontWeight: '800' },
    suitGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    suitGridLandscape: { maxWidth: 210 },
    suitButton: {
      alignItems: 'center',
      backgroundColor: colors.surfaceStrong,
      borderColor: colors.line,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 8,
      justifyContent: 'center',
      minHeight: 52,
      paddingHorizontal: 12,
      width: '48.7%',
    },
    suitButtonLandscape: { width: '100%' },
    suitMark: { color: colors.text, fontSize: 22, fontWeight: '800' },
    redSuitMark: { color: '#b2252b' },
    transparentCameraSuitMark: {
      color: '#ffffff',
      textShadowColor: '#000000',
      textShadowOffset: { height: 1, width: 0 },
      textShadowRadius: 4,
    },
    rankGrid: { flex: 1, flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    rankGridLandscape: { alignSelf: 'stretch' },
    rankCell: { width: '31.8%' },
    rankCellLandscape: { width: '23.6%' },
    jokerRow: { flexDirection: 'row', gap: 8 },
    jokerRowLandscape: { flexDirection: 'column', minWidth: 120 },
    symbolPanel: { gap: 8 },
    inputLabel: { color: colors.muted, fontSize: 16, fontWeight: '700' },
    symbolInputRow: { gap: 10 },
    symbolInputRowLandscape: { alignItems: 'stretch', flexDirection: 'row' },
    symbolInput: {
      backgroundColor: colors.surfaceStrong,
      borderColor: colors.line,
      borderRadius: 8,
      borderWidth: 1,
      color: colors.text,
      fontSize: 32,
      fontWeight: '800',
      minHeight: 58,
      paddingHorizontal: 12,
      textAlign: 'center',
    },
    rawCommandInput: { fontSize: 18, fontWeight: '700', textAlign: 'left' },
    transparentCameraInput: { backgroundColor: 'transparent', borderColor: '#ffffff75', color: '#ffffff' },
    symbolInputLandscape: { flex: 1, minWidth: 180 },
    disabledInput: { opacity: 0.46 },
    espGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    espCell: { width: '48.7%' },
    espCellLandscape: { width: '31.8%' },
    statusPanel: { borderTopColor: colors.line, borderTopWidth: 1, gap: 8, paddingTop: 16 },
    statusLine: { gap: 3 },
    statusLabel: { color: colors.muted, fontWeight: '700' },
    statusValue: { color: colors.text, fontSize: 16, fontWeight: '600' },
    logEntry: { backgroundColor: '#ffffff94', borderLeftColor: colors.accent, borderLeftWidth: 3, color: colors.muted, paddingHorizontal: 8, paddingVertical: 6 },
    settingsGroup: { gap: 8 },
    cameraStyleOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    cameraStyleOption: {
      alignItems: 'center',
      backgroundColor: colors.surfaceStrong,
      borderColor: colors.line,
      borderRadius: 8,
      borderWidth: 1,
      flexBasis: 120,
      flexGrow: 1,
      justifyContent: 'center',
      minHeight: 44,
      paddingHorizontal: 8,
    },
    opacitySliderGroup: { gap: 8, paddingTop: 4 },
    opacitySliderHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
    opacitySliderValue: { color: colors.muted, fontSize: 14, fontWeight: '800' },
    opacitySliderTrack: { backgroundColor: colors.line, borderRadius: 999, height: 34, justifyContent: 'center' },
    opacitySliderFill: { backgroundColor: colors.accent, bottom: 0, left: 0, position: 'absolute', top: 0 },
    opacitySliderThumb: {
      backgroundColor: colors.surfaceStrong,
      borderColor: colors.accent,
      borderRadius: 999,
      borderWidth: 2,
      height: 28,
      marginLeft: -14,
      position: 'absolute',
      width: 28,
    },
    aboutPanel: { alignItems: 'center', gap: 4 },
    aboutIcon: { height: 72, width: 72 },
    aboutImage: { aspectRatio: 1, borderRadius: 8, maxWidth: 260, width: '50%' },
    aboutText: { color: colors.text, fontSize: 16, fontWeight: '700', textAlign: 'center' },
    markdownContainer: { alignSelf: 'stretch', gap: 8 },
    markdownHeading: { color: colors.text, fontWeight: '800' },
    markdownHeadingOne: { fontSize: 22, lineHeight: 28, textAlign: 'center' },
    markdownHeadingTwo: { fontSize: 19, lineHeight: 25 },
    markdownHeadingThree: { fontSize: 17, lineHeight: 23 },
    markdownParagraph: { color: colors.text, fontSize: 16, lineHeight: 23 },
    markdownListRow: { alignItems: 'flex-start', flexDirection: 'row', gap: 8 },
    markdownBullet: { color: colors.accent, fontSize: 18, fontWeight: '900', lineHeight: 23 },
    markdownListText: { color: colors.text, flex: 1, fontSize: 16, lineHeight: 23 },
    markdownStrong: { fontWeight: '900' },
    markdownEmphasis: { fontStyle: 'italic' },
    markdownCode: {
      backgroundColor: colors.surface,
      borderColor: colors.line,
      borderRadius: 4,
      borderWidth: 1,
      color: colors.text,
      fontFamily: 'monospace',
      fontSize: 14,
      paddingHorizontal: 4,
    },
    scrollHint: {
      alignItems: 'center',
      alignSelf: 'center',
      backgroundColor: colors.accent,
      borderColor: colors.accentStrong,
      borderRadius: 999,
      borderWidth: 1,
      bottom: 10,
      flexDirection: 'row',
      gap: 6,
      minHeight: 34,
      paddingHorizontal: 12,
      position: 'absolute',
    },
    scrollHintText: { color: '#ffffff', fontSize: 13, fontWeight: '800' },
    cameraSafeArea: { backgroundColor: '#050607', flex: 1 },
    cameraScreen: { backgroundColor: '#050607', flex: 1, overflow: 'hidden' },
    cameraPreview: { ...StyleSheet.absoluteFill },
    cameraFallback: {
      ...StyleSheet.absoluteFill,
      alignItems: 'center',
      backgroundColor: '#101417',
      gap: 14,
      justifyContent: 'center',
      padding: 24,
    },
    cameraFallbackTitle: { color: '#ffffff', fontSize: 22, fontWeight: '800', textAlign: 'center' },
    cameraFallbackText: { color: '#cfd8dc', fontSize: 15, lineHeight: 21, maxWidth: 360, textAlign: 'center' },
    viewfinderLayer: { ...StyleSheet.absoluteFill, alignItems: 'center', justifyContent: 'center' },
    viewfinderHorizontalLine: { backgroundColor: '#ffffff42', height: 1, position: 'absolute', width: '100%' },
    viewfinderVerticalLine: { backgroundColor: '#ffffff42', height: '100%', position: 'absolute', width: 1 },
    viewfinderFrame: { borderColor: '#ffffff78', borderRadius: 8, borderWidth: 1, height: '58%', width: '76%' },
    cameraGestureLayer: { ...StyleSheet.absoluteFill },
    fakePauseOverlay: { ...StyleSheet.absoluteFill, alignItems: 'center', justifyContent: 'center' },
    fakePauseText: {
      backgroundColor: '#00000060',
      borderColor: '#ffffff70',
      borderRadius: 8,
      borderWidth: 1,
      color: '#ffffff',
      fontSize: 20,
      fontWeight: '900',
      letterSpacing: 0,
      paddingHorizontal: 18,
      paddingVertical: 10,
    },
    cameraHud: {
      alignItems: 'center',
      backgroundColor: '#00000045',
      flexDirection: 'row',
      justifyContent: 'space-between',
      left: 0,
      minHeight: 54,
      paddingHorizontal: 14,
      paddingVertical: 10,
      position: 'absolute',
      right: 0,
      top: 0,
    },
    cameraHudIos: { backgroundColor: '#11111165', borderBottomColor: '#ffffff30', borderBottomWidth: 1 },
    cameraHudFantasy: { backgroundColor: '#0928279c', borderBottomColor: '#70fff070', borderBottomWidth: 1 },
    recordingBadge: {
      alignItems: 'center',
      backgroundColor: '#00000080',
      borderColor: '#ffffff42',
      borderRadius: 999,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 7,
      minHeight: 32,
      paddingHorizontal: 10,
    },
    recordingDot: { backgroundColor: '#ff2f3f', borderRadius: 999, height: 10, width: 10 },
    recordingText: { color: '#ffffff', fontSize: 13, fontWeight: '900' },
    cameraTitleButton: { alignItems: 'center', borderRadius: 8, flex: 1, justifyContent: 'center', marginHorizontal: 8, minHeight: 36, paddingHorizontal: 8 },
    cameraHudTitleText: { color: '#ffffff', fontSize: 16, fontWeight: '900', textAlign: 'center' },
    cameraHudText: { color: '#ffffff', fontSize: 13, fontWeight: '800' },
    cameraBottomHud: { alignItems: 'center', bottom: 14, flexDirection: 'row', gap: 10, justifyContent: 'center', left: 12, position: 'absolute', right: 12 },
    fakePauseButton: {
      alignItems: 'center',
      backgroundColor: '#00000085',
      borderColor: '#ffffff55',
      borderRadius: 999,
      borderWidth: 1,
      justifyContent: 'center',
      minHeight: 42,
      minWidth: 94,
      paddingHorizontal: 14,
    },
    fakePauseButtonText: { color: '#ffffff', fontSize: 14, fontWeight: '900' },
    cameraZoomBadge: {
      alignItems: 'center',
      backgroundColor: '#00000085',
      borderColor: '#ffffff55',
      borderRadius: 999,
      borderWidth: 1,
      justifyContent: 'center',
      minHeight: 42,
      minWidth: 112,
      paddingHorizontal: 14,
    },
    cameraZoomText: { color: '#ffffff', fontSize: 14, fontWeight: '900' },
    fullScreenOverlay: { ...StyleSheet.absoluteFill, backgroundColor: '#00000030', paddingHorizontal: 12, paddingTop: 66 },
    transparentFullScreenOverlay: { backgroundColor: 'transparent' },
    fullScreenOverlayActions: { flexDirection: 'row', gap: 8, justifyContent: 'space-between' },
    overlayActionButton: {
      alignItems: 'center',
      backgroundColor: '#11181dcc',
      borderColor: '#ffffff55',
      borderRadius: 8,
      borderWidth: 1,
      justifyContent: 'center',
      minHeight: 44,
      paddingHorizontal: 12,
    },
    overlayIconButton: {
      alignItems: 'center',
      backgroundColor: '#11181dcc',
      borderColor: '#ffffff55',
      borderRadius: 8,
      borderWidth: 1,
      justifyContent: 'center',
      minHeight: 44,
      minWidth: 48,
      paddingHorizontal: 12,
    },
    transparentOverlayActionButton: { backgroundColor: 'transparent', borderColor: '#ffffff70' },
    overlayActionButtonText: { color: '#ffffff', fontSize: 15, fontWeight: '800' },
    transparentOverlayActionButtonText: {
      color: '#ffffff',
      textShadowColor: '#000000',
      textShadowOffset: { height: 1, width: 0 },
      textShadowRadius: 3,
    },
    fullScreenOverlayContent: { flexGrow: 1, justifyContent: 'center', paddingBottom: 20, paddingTop: 12 },
    fullScreenOverlayContentLandscape: { paddingHorizontal: 24, paddingVertical: 12 },
    fullScreenControlSurface: { backgroundColor: '#ffffffd9', borderColor: '#ffffff90', borderRadius: 8, borderWidth: 1, padding: 12 },
    transparentFullScreenControlSurface: { backgroundColor: 'transparent', borderColor: 'transparent' },
  });
}

export type AppStyles = ReturnType<typeof createStyles>;
